Wagtail 6.0
torchbox/wagtail-purge pull request #10
Opened 2024-02-26 10:36 UTC by katdom13

[Support Ticket](https://torchbox.monday.com/boards/1124794299/pulses/1396935580)

## [Wagtail 6.0 release notes](https://docs.wagtail.org/en/stable/releases/6.0.html)

### Summary of changes

- Added Wagtail 6.0 compatibility
- Added tests for Django 5.0
- Added tests for Python 3.12

2024-02-26 15:53 UTC, rachelhsmith approved these changes
Hi @katdom13 this looks good to me!

2024-03-06 09:11 UTC, zerolab commented on wagtail_purge/wagtail_hooks.py
> +
This if statement is not needed since install requires `wagtail>=5.2`

2024-03-07 04:21 UTC, katdom13 commented on wagtail_purge/wagtail_hooks.py
> +
Hi @zerolab ,
Good shout. Please see latest change:
https://github.com/torchbox/wagtail-purge/pull/10/commits/c4f063195e6ee0a9573749e456a11caee546a1f0

Thanks!

2024-03-07 18:01 UTC, zerolab requested changes

2024-03-07 18:01 UTC, zerolab commented on CHANGELOG.md
> +- Support for Wagtail version 5.2 and above
```suggestion
- Updated supported Wagtail versions to 5.2 and above
```

2024-03-07 18:01 UTC, zerolab commented on wagtail_purge/wagtail_hooks.py
> +from wagtail import hooks, VERSION as WAGTAIL_VERSION
```suggestion
from wagtail import hooks
```

since `WAGTAIL_VERSION` is not used anywhere

2024-03-08 02:27 UTC, katdom13 commented on CHANGELOG.md
> +- Support for Wagtail version 5.2 and above
Thanks @zerolab ,
Applied this suggestion

2024-03-08 02:28 UTC, katdom13 commented on wagtail_purge/wagtail_hooks.py
> +from wagtail import hooks, VERSION as WAGTAIL_VERSION
Applied this too

2024-03-18 09:15 UTC, merged